### ISSUE TITLE
Install failed with error code

### ISSUE THREAD

**Issue by akmedia** [Hackworth/VeraHomeKitBridge#5]
Please help me to get through this. I'm a noob but can code/debug to some extent. Trying to setup this in my Raspberry pi. Any help is much appreciated and thanks for all your efforts to bring this closer to iOS. 

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/VeraHomeKitBridge/app.js:6:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
npm ERR! VeraHomeKitBridge@1.0.0 start: `node app.js`
npm ERR! `sh "-c" "node app.js"` failed with 8
npm ERR! 
npm ERR! Failed at the VeraHomeKitBridge@1.0.0 start script.
npm ERR! This is most likely a problem with the VeraHomeKitBridge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls VeraHomeKitBridge
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.6+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! cwd /home/pi/VeraHomeKitBridge
npm ERR! node -v v0.10.2
npm ERR! npm -v 1.2.15
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/VeraHomeKitBridge/npm-debug.log
npm ERR! not ok code 0

**Comment by rafale77** [comment]
Probably want to install a newer nodejs version. Try 12.7.

**Comment by damianxd** [comment]
try to do

`npm install request`

on the same folder that app.js is and then run the program again
